// eslint-disable-next-line @typescript-eslint/typedef, @typescript-eslint/explicit-function-return-type, @typescript-eslint/explicit-module-boundary-types
export const ACCENT_COLORS = [
	'#fda29b',
	'#feb273',
	'#fec84b',
	'#b0d364',
	'#8ddd8b',
	'#7de4f2',
	'#84caff',
	'#a4bcfd',
	'#faa7c5',
	'#bdb4fe',
	'#fecdca',
	'#fddcab',
	'#fedf89',
	'#c9eb81',
	'#b1f2b0',
	'#b9f9fe',
	'#b2ddff',
	'#c7d7fe',
	'#fccedc',
	'#d9d6fe',
	'#fee4e2',
	'#ffead5',
	'#fef0c7',
	'#ddf8a5',
	'#d9f9d9',
	'#daf6f8',
	'#d1e9ff',
	'#e0eaff',
	'#fce7ef',
	'#ebe9fe',
] as const;
