// eslint-disable-next-line @typescript-eslint/typedef, @typescript-eslint/explicit-function-return-type, @typescript-eslint/explicit-module-boundary-types
export const INDUSTRIES = [
	{ id: 1, name: 'Administrative/Consultant' },
	{ id: 2, name: 'Travel Agency' },
	{ id: 3, name: 'Marketing/Advertising' },
	{ id: 4, name: 'Online Business' },
	{ id: 5, name: 'Retail Sales' },
	{ id: 6, name: 'Technology Services' },
	{ id: 7, name: 'Telecommunications' },
	{ id: 8, name: 'Video Production' },
	{ id: 9, name: 'Architecture/Interior Design' },
	{ id: 10, name: 'Building Construction' },
	{ id: 11, name: 'Education/Training' },
	{ id: 12, name: 'Real Estate' },
	{ id: 13, name: 'Insurance' },
	{ id: 14, name: 'Auditing' },
	{ id: 15, name: 'Banking' },
	{ id: 16, name: 'Financial Service/Tax Preparation' },
	{ id: 17, name: 'FMCG' },
	{ id: 18, name: 'Pharmacy' },
	{ id: 19, name: 'Health/Medical Care' },
	{ id: 20, name: 'Motor Vehicle Services' },
	{ id: 21, name: 'Beauty Salon' },
	{ id: 22, name: 'Fitness' },
	{ id: 23, name: 'Personal Services' },
	{ id: 24, name: 'Warehouse' },
	{ id: 25, name: 'Sales' },
	{ id: 26, name: 'Securities/Trading' },
	{ id: 27, name: 'Printing' },
	{ id: 28, name: 'Restaurant/Hotel' },
	{ id: 29, name: 'Fashion/Lifestyle' },
	{ id: 30, name: 'Food & Baverage' },
	{ id: 31, name: 'Freight/Logistics' },
	{ id: 32, name: 'Export/Import' },
	{ id: 33, name: 'Hospital' },
	{ id: 34, name: 'Electrical/Electronics' },
	{ id: 35, name: 'Human Resources' },
] as const;
