export * from './wgc-comment-attachment-list/wgc-comment-attachment-list.component';
export * from './wgc-comment-box/wgc-comment-box.component';
export * from './wgc-comment-content/wgc-comment-content.component';
export * from './wgc-comment-image-list/wgc-comment-image-list.component';
export * from './wgc-comment-link-list/wgc-comment-link-list.component';
export * from './wgc-comment-list/wgc-comment-list.component';
export * from './wgc-comment.module';
export * from './resources';
export * from './interfaces';
